
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml




# Custom config
lovelace:
  mode: yaml
  resources:
    - url: /local/mini-media-player-bundle.js?v=1.11.0
      type: module

  
  dashboards:
    lovelace-generated:
      mode: yaml
      filename: testDash.yaml
      title: testDash
      show_in_sidebar: true



spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  
spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key