
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml




# Custom config
lovelace:
  mode: yaml
  resources:
    - url: /local/mini-media-player-bundle.js?v=1.11.0
      type: module

    - url: /local/community/spotify-card/spotify-card.js
      type: module

  
  dashboards:
    lights-dashboard:
      mode: yaml
      filename: lovelace/lights-dashboard.yaml
      title: Lights
      show_in_sidebar: true

    speakers-dashboard:
      mode: yaml
      filename: lovelace/speakers-dashboard.yaml
      title: Speakers
      show_in_sidebar: true
          


spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  
spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key